#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
coffee="$DIR/../node_modules/.bin/coffee"
source_dir="$DIR/../source"
docs_dir="$DIR/../docs"
build_dir="$DIR/../build"
npm_dir="$DIR/.."

clean() {
  clean-build-dir
}

clean-build-dir() {
  rm -rf $build_dir/**/*.js $build_dir/**/*.map
}

build() {
  build-source
  build-readme
}

build-source() {
  $coffee -cmb -o $build_dir $source_dir
}

build-readme() {
  cat $docs_dir/MarkdownDriven.coffee.md > $npm_dir/README.md
  echo -e "\n--------------------------------------------------------------------------------\n" >> $npm_dir/README.md
  cat $npm_dir/LICENSE.md >> $npm_dir/README.md
}

build-specs() {
  $coffee "$DIR/../support/build-specs.coffee"
}

argv=("$*")
for arg in $argv; do eval ${arg}; done
